
#ifndef __IMX6_SDRAM_SPL_CONFIG_H
#define __IMX6_SDRAM_SPL_CONFIG_H

#ifdef CONFIG_SPL

#define CONFIG_SPL_FRAMEWORK

#define CONFIG_SYS_THUMB_BUILD
#define CONFIG_SPL_LDSCRIPT	    "arch/arm/imx-common/u-boot-spl.lds"
#define CONFIG_SPL_START_S_PATH "arch/arm/cpu/armv7"

#define CONFIG_SPL_RANGE_BEGIN      0x17780000
#define CONFIG_SPL_RANGE_END        0x17800000
#define CONFIG_SYS_TEXT_BASE		0x17800000

#define CONFIG_SPL_TEXT_BASE        0x17780000
#define CONFIG_SPL_MAX_SIZE		    0x10000
#define CONFIG_SYS_SPL_MALLOC_START	0x17790000
#define CONFIG_SYS_SPL_MALLOC_SIZE	0x10000
#define CONFIG_SPL_STACK_SIZE       0x10000
#define CONFIG_SPL_STACK            0x177affb8
#define CONFIG_SPL_SMP_STACK        0x177c0000

#define CONFIG_SPL_LIBCOMMON_SUPPORT
#define CONFIG_SPL_LIBGENERIC_SUPPORT
#define CONFIG_SPL_SERIAL_SUPPORT

/* NAND support */
#if defined(CONFIG_SPL_NAND_SUPPORT)
#define CONFIG_SPL_NAND_MXS
#define CONFIG_SPL_DMA_SUPPORT
#endif

/* MMC support */
#if defined(CONFIG_SPL_MMC_SUPPORT)
#define CONFIG_SYS_MONITOR_LEN  (CONFIG_SYS_U_BOOT_MAX_SIZE_SECTORS/2*1024)
#endif

#endif

#endif
